const FETCH_PHONES_REQUEST = 'phone-shop/phones/FETCH_PHONES_REQUEST';
const FETCH_PHONES_SUCCESS = 'phone-shop/phones/FETCH_PHONES_SUCCESS';
const FETCH_PHONES_FAILURE = 'phone-shop/phones/FETCH_PHONES_FAILURE';

export default {
  FETCH_PHONES_REQUEST,
  FETCH_PHONES_SUCCESS,
  FETCH_PHONES_FAILURE
};